# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            sshPublicKey: '${MYPUB_KEY}'
            sshKeySecureFile: 'id_rsa'
         
        - bash: |
           git checkout gh-pages
           displayName: Switch to documentation branch
         
        - bash: |
             git config --global user.email "akarsh.modi@gmail.com"
             git config --global user.name "Test Checkin"
             git add .
             git commit -m "Documentation generated and committed to gh-pages"
             git push origin gh-pages
          displayName: Commit and push

